# Generated by Django 5.0.6 on 2024-06-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmarket', '0002_vehicleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
