# Generated by Django 5.0.6 on 2024-06-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmarket', '0005_vehicle_gearbox_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
