# Generated by Django 5.0.6 on 2024-06-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmarket', '0006_vehicle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, choices=[('UNIVERSAL', 'Універсал'), ('SEDAN', 'Седан'), ('HATCHBACK', 'Хетчбек'), ('SUV', 'Позашляховик'), ('COUPE', 'Купе'), ('CONVERTIBLE', 'Кабріолет'), ('MINIVAN', 'Мінівен'), ('PICKUP', 'Пікап'), ('LIMOUSINE', 'Лімузин'), ('LIFTBACK', 'Ліфтбек'), ('ROADSTER', 'Родстер'), ('FASTBACK', 'Фастбек'), ('MICROVAN', 'Мікровен')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Chevrolet', 'Chevrolet'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Kia', 'Kia'), ('Lexus', 'Lexus'), ('Mazda', 'Mazda'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Toyota', 'Toyota'), ('Harley-Davidson', 'Harley-Davidson'), ('Yamaha', 'Yamaha'), ('Ducati', 'Ducati'), ('Volvo', 'Volvo'), ('Scania', 'Scania'), ('Man', 'Man'), ('Iveco', 'Iveco'), ('DAF', 'DAF'), ('Renault', 'Renault'), ('Neoplan', 'Neoplan'), ('Setra', 'Setra'), ('Hobby', 'Hobby'), ('Volkswagen', 'Volkswagen')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('AWD', 'Повний'), ('FWD', 'Передній'), ('RWD', 'Задній')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('GASOLINE', 'Бензин'), ('GAS', 'Газ'), ('LPG', 'Газ пропан-бутан'), ('CNG', 'Газ метан'), ('HYBRID_HEV', 'Гібрид (HEV)'), ('HYBRID_PHEV', 'Гібрид (PHEV)'), ('DIESEL', 'Дизель'), ('ELECTRIC', 'Електро')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='gearbox_type',
            field=models.CharField(blank=True, choices=[('AUTO', 'Автомат'), ('MANUAL', 'Механіка'), ('ROBOT', 'Робот'), ('VARIATOR', 'Варіатор'), ('TIPTRONIC', 'типтронік')], default='AUTO', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='power',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='region',
            field=models.CharField(choices=[('ZH', 'Житомирська'), ('VI', 'Вінницька'), ('KY', 'Київська'), ('VN', 'Волинська'), ('DN', 'Дніпропетровська'), ('DP', 'Донецька'), ('IV', 'Івано-Франківська'), ('KH', 'Харківська'), ('KR', 'Херсонська'), ('KM', 'Хмельницька'), ('CK', 'Черкаська'), ('CH', 'Чернігівська'), ('CV', 'Чернівецька'), ('KK', 'Кіровоградська'), ('KV', 'Київська'), ('LH', 'Луганська'), ('LV', 'Львівська'), ('MK', 'Миколаївська'), ('OD', 'Одеська'), ('PL', 'Полтавська'), ('RV', 'Рівненська'), ('SC', 'Сумська'), ('TP', 'Тернопільська'), ('ZC', 'Закарпатська'), ('ZP', 'Запорізька')], max_length=20),
        ),
    ]
