# Generated by Django 5.0.6 on 2024-06-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmarket', '0007_alter_vehicle_body_type_alter_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vin_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
