# Generated by Django 5.0.6 on 2024-06-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmarket', '0010_alter_vehicle_body_type_alter_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
