import type { Metadata } from "next";
import { Public_Sans } from "next/font/google";
import "@/styles/globals.css";
import Header from "@/components/Header/Header";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { CurrencyProvider } from "@/providers/CurrencyContext";
import { getServerSession } from "next-auth";
import { authConfig } from "@/configs/auth";
import SessionProvider from "@/providers/SessionProvider";

const publicSans = Public_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession(authConfig);

    return (
        <html lang="ua">
            <body className={publicSans.className}>
                <SessionProvider session={session}>
                    <AntdRegistry>
                        <CurrencyProvider>
                            <Header />
                            {children}
                        </CurrencyProvider>
                    </AntdRegistry>
                </SessionProvider>
            </body>
        </html>
    );
}
